#:import OneLineIconItem uix.OneLineIconItem
#:import Gradient kivy_gradient.Gradient


<MeTap>:
    name: "me"
    icon: "account-circle-outline"
    text: app.lang["Me"]
	MDBoxLayout:
		size_hint: 1, 1
		orientation: 'vertical'
        MDBoxLayout:
            size_hint: 1, 0.4
            pos_hint: {'top': 1}
            padding: dp(20)
            spacing: dp(30)
            md_bg_color: 1, 1, 1, 1
            radius: [0, 0, dp(20), dp(20)]
            canvas:
                Color:
                    rgba: rgba('#111111')
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [0, 0, dp(18), dp(18)]

                Color:
                    rgba: rgba('#ffffff')
                RoundedRectangle:
                    pos: self.x, self.y + dp(2)
                    size: self.size
                    radius: [0, 0, dp(20), dp(20)]
                    texture: Gradient.horizontal(rgba("#FFD700"), self.theme_cls.bg_normal)

            MDBoxLayout:
                orientation: 'vertical'
                pos_hint: {'center_y': 0.5}
                adaptive_height: True
                disabled: not app.username
                opacity: 0 if not app.username else 1
                MDLabel:
                    text: app.username
                    halign: 'right'
                    size_hint: 1, None
                    height: dp(50)
                    color: self.theme_cls.text_color
                MDLabel:
                    text: app.email
                    halign: 'right'
                    color: self.theme_cls.text_color
                    size_hint: 1, None
                    height: dp(50)
            FitImage:
                id: user_image
                source: app.user.profile_picture_url() if app.username else "assets/images/account.jpg"
                size_hint: None, .9
                radius: self.height/2
                pos_hint: {'center_y': 0.5}
                width: self.height
                disabled: not app.username
                opacity: 0 if not app.username else 1
                canvas.after:
                    Color:
                        rgba: rgba("#FFD700")
                    Line:
                        width: dp(2)
                        circle: self.center_x, self.center_y, self.height/2

    	MDList:
    	    size_hint: 1, 1
#            OneLineIconItem:
#                text: "History"
#                icon: "history"
            OneLineIconItem:
                text: app.lang["Liked"]
                icon: "heart"
                on_release:
                    if app.username: app.root.current = "favorite_screen"
                    if not app.username: app.request_login()

#            OneLineIconItem:
#                text: app.lang["Settings"]
#                icon: "cog-outline"
            OneLineIconItem:
                text: app.lang["Privacy Policy"]
                icon: "script-text-key-outline"
                on_release:
                    app.root.current = "privacy_policy"
            OneLineIconItem:
                text: app.lang["About"]
                icon: "information-outline"
                on_release:
                    app.root.current = "about"
            OneLineIconItem:
                text: app.lang["Log Out" if app.username else "Login"]
                icon: "logout" if app.username else "login"
                on_release:
                    if app.username: app.logout()
                    if not app.username: app.root.current = "login"

#    MDIconButton:
#        icon: 'pencil'
#        theme_text_color: "Custom"
#        icon_color: 0,0,0,1
#        pos_hint: {"top": 1}
#        disabled: not app.username
#        opacity: 0 if not app.username else 1

    MDRaisedButton:
        text: app.lang["Login"]
        pos_hint: {'center_x': 0.5}
        center_y: user_image.center_y
        disabled: bool(app.username)
        opacity: 0 if app.username else 1
        on_release: app.root.current = "login"



