#:import TagScrollView uix.TagScrollView
#:import ItemDisplayLine uix.ItemDisplayLine
#:import ScrollEffect kivy.effects.scroll.ScrollEffect

<ShopTap>:
    name: "shop"
    icon: "shopping-outline"
    text: app.lang["Shop"]

    ScrollView:
        do_scroll_x: False
        effect_cls: ScrollEffect
        MDGridLayout:
            id: displays
            cols: 1
            spacing: dp(10)
            orientation: "lr-tb"
            padding: 0, dp(57), 0, 0
            adaptive_height: True

    MDTextField:
        pos: dp(10), root.height - dp(47)
        size_hint: None, None
        mode: "round"
        size: root.width - dp(20), dp(37)
        hint_text: app.lang["Search"]
        icon_right: "magnify"
        halign: "right"
        line_color_normal: 1,1,1,0
        line_color_focus: 1,1,1,0
        next: root.search

    MDIconButton:
        icon: "plus"
        md_bg_color: self.theme_cls.accent_color
        pos: dp(20), dp(20)
        on_release:
            app.root.get_screen("edit_item_screen").new()
            app.root.current = "edit_item_screen"
